#!/usr/bin/env node
/**
 * Build script: generates lib/data/kz-map.ts from a GADM v4.1 admin-1 GeoJSON
 * for Kazakhstan, projecting polygons + dealer city lat/lng into a shared SVG
 * viewBox so dealer pins always sit on the right region. Re-run after editing
 * dealer coordinates or swapping the source GeoJSON.
 *
 *   node scripts/build-kz-map.mjs
 *
 * Source: https://geodata.ucdavis.edu/gadm/gadm4.1/json/gadm41_KAZ_1.json
 * License: GADM data is free for academic/non-commercial use; we ship only the
 * projected SVG paths derived from it.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { geoMercator, geoPath, geoCentroid } from 'd3-geo'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '..')
const SOURCE = resolve(HERE, '.gadm-kaz-1.json')
const OUT = resolve(ROOT, 'lib/data/kz-map.ts')

const VIEWBOX_WIDTH = 1024
const VIEWBOX_HEIGHT = 700
const VIEWBOX_PAD = 12
const PATH_PRECISION = 0
// Min perpendicular distance (in viewBox units) below which a vertex is dropped.
// At viewBox 1024×700 a value of 0.6 trims ~80% of GADM's shoreline detail
// without visibly changing the country silhouette.
const SIMPLIFY_TOLERANCE = 0.6

// GADM 4.1 NAME_1 → display names (Russian / Kazakh).
// Names follow the 2022 reform terminology where the polygon still maps 1:1
// (e.g. SouthKazakhstan is shown as "Туркестанская"). Polygons that were split
// by the 2022 reform (Almaty → Almaty + Jetisu, Qaraghandy → Karaganda + Ulytau,
// EastKazakhstan → East Kazakhstan + Abai) remain as single regions — GADM 4.1
// hasn't been updated for the split yet.
const REGION_NAMES = {
  Almaty:          { id: 'almaty',    ru: 'Алматинская',           kk: 'Алматы облысы',           shortRu: 'Алматинская',  shortKk: 'Алматы' },
  Aqmola:          { id: 'aqmola',    ru: 'Акмолинская',           kk: 'Ақмола облысы',           shortRu: 'Акмолинская',  shortKk: 'Ақмола' },
  'Aqtöbe':        { id: 'aktobe',    ru: 'Актюбинская',           kk: 'Ақтөбе облысы',           shortRu: 'Актобе',       shortKk: 'Ақтөбе' },
  Atyrau:          { id: 'atyrau',    ru: 'Атырауская',            kk: 'Атырау облысы',           shortRu: 'Атырау',       shortKk: 'Атырау' },
  EastKazakhstan:  { id: 'east',      ru: 'Восточно-Казахстанская', kk: 'Шығыс Қазақстан облысы',  shortRu: 'ВКО',          shortKk: 'ШҚО' },
  Mangghystau:     { id: 'mangystau', ru: 'Мангистауская',         kk: 'Маңғыстау облысы',        shortRu: 'Мангистау',    shortKk: 'Маңғыстау' },
  NorthKazakhstan: { id: 'north',     ru: 'Северо-Казахстанская',  kk: 'Солтүстік Қазақстан облысы', shortRu: 'СКО',       shortKk: 'СҚО' },
  Pavlodar:        { id: 'pavlodar',  ru: 'Павлодарская',          kk: 'Павлодар облысы',         shortRu: 'Павлодар',     shortKk: 'Павлодар' },
  Qaraghandy:      { id: 'karagandy', ru: 'Карагандинская',        kk: 'Қарағанды облысы',        shortRu: 'Караганда',    shortKk: 'Қарағанды' },
  Qostanay:        { id: 'kostanay',  ru: 'Костанайская',          kk: 'Қостанай облысы',         shortRu: 'Костанай',     shortKk: 'Қостанай' },
  Qyzylorda:       { id: 'kyzylorda', ru: 'Кызылординская',        kk: 'Қызылорда облысы',        shortRu: 'Кызылорда',    shortKk: 'Қызылорда' },
  SouthKazakhstan: { id: 'turkistan', ru: 'Туркестанская',         kk: 'Түркістан облысы',        shortRu: 'Туркестан',    shortKk: 'Түркістан' },
  WestKazakhstan:  { id: 'west',      ru: 'Западно-Казахстанская', kk: 'Батыс Қазақстан облысы',  shortRu: 'ЗКО',          shortKk: 'БҚО' },
  Zhambyl:         { id: 'zhambyl',   ru: 'Жамбылская',            kk: 'Жамбыл облысы',           shortRu: 'Жамбыл',       shortKk: 'Жамбыл' },
}

// Dealer cities — lat/lng is the single source of truth; cx/cy in dealers.ts
// is regenerated by this script from the same projection that produces the
// region polygons, so pins always align.
const DEALER_CITIES = [
  { id: 'shymkent',  lat: 42.3417, lng: 69.5901 },
  { id: 'aktobe',    lat: 50.2796, lng: 57.2072 },
  { id: 'taraz',     lat: 42.9000, lng: 71.3667 },
  { id: 'astana',    lat: 51.1605, lng: 71.4704 },
  { id: 'karagandy', lat: 49.8047, lng: 73.1094 },
  { id: 'uralsk',    lat: 51.2333, lng: 51.3667 },
  { id: 'kyzylorda', lat: 44.8479, lng: 65.4823 },
]

const SOURCE_URL = 'https://geodata.ucdavis.edu/gadm/gadm4.1/json/gadm41_KAZ_1.json'

async function loadGeoJson() {
  if (!existsSync(SOURCE)) {
    console.log(`Fetching ${SOURCE_URL}`)
    const response = await fetch(SOURCE_URL)
    if (!response.ok) {
      throw new Error(`Failed to download GADM source: ${response.status} ${response.statusText}`)
    }
    const buf = Buffer.from(await response.arrayBuffer())
    writeFileSync(SOURCE, buf)
  }
  return JSON.parse(readFileSync(SOURCE, 'utf8'))
}

function round(value, digits = PATH_PRECISION) {
  const f = 10 ** digits
  return Math.round(value * f) / f
}

function trimPath(d) {
  return d.replace(/-?\d+\.\d+/g, (n) => String(round(Number(n))))
}

// Iterative Douglas-Peucker: keep first/last, recursively retain the vertex
// with the largest perpendicular distance from the chord whenever that
// distance exceeds the tolerance. Operates on a single closed ring.
function simplifyRing(points, tolerance) {
  if (points.length <= 3) return points
  const sqTol = tolerance * tolerance
  const keep = new Uint8Array(points.length)
  keep[0] = 1
  keep[points.length - 1] = 1
  const stack = [[0, points.length - 1]]
  while (stack.length) {
    const [first, last] = stack.pop()
    let maxSq = 0
    let index = -1
    const [ax, ay] = points[first]
    const [bx, by] = points[last]
    const dx = bx - ax
    const dy = by - ay
    const denom = dx * dx + dy * dy
    for (let i = first + 1; i < last; i += 1) {
      const [px, py] = points[i]
      let sq
      if (denom === 0) {
        const ex = px - ax
        const ey = py - ay
        sq = ex * ex + ey * ey
      } else {
        let t = ((px - ax) * dx + (py - ay) * dy) / denom
        if (t < 0) t = 0
        else if (t > 1) t = 1
        const ex = ax + t * dx - px
        const ey = ay + t * dy - py
        sq = ex * ex + ey * ey
      }
      if (sq > maxSq) {
        maxSq = sq
        index = i
      }
    }
    if (maxSq > sqTol && index !== -1) {
      keep[index] = 1
      stack.push([first, index], [index, last])
    }
  }
  const out = []
  for (let i = 0; i < points.length; i += 1) {
    if (keep[i]) out.push(points[i])
  }
  return out
}

function simplifyFeature(feature, tolerance) {
  const simplifyRings = (rings) =>
    rings
      .map((ring) => {
        if (ring.length < 4) return ring
        const simplified = simplifyRing(ring, tolerance)
        // A polygon ring needs at least 4 points (closed). If we dropped too
        // many, fall back to the original to avoid invalid geometry.
        return simplified.length >= 4 ? simplified : ring
      })
      .filter((ring) => ring.length >= 4)

  const geom = feature.geometry
  if (geom.type === 'Polygon') {
    geom.coordinates = simplifyRings(geom.coordinates)
  } else if (geom.type === 'MultiPolygon') {
    geom.coordinates = geom.coordinates.map(simplifyRings).filter((p) => p.length > 0)
  }
  return feature
}

function projectFeature(feature, projection) {
  const projectRing = (ring) =>
    ring.map(([lng, lat]) => {
      const xy = projection([lng, lat])
      return xy ?? [0, 0]
    })
  const projectPolygon = (rings) => rings.map(projectRing)
  const geom = feature.geometry
  const next = { type: geom.type, coordinates: null }
  if (geom.type === 'Polygon') next.coordinates = projectPolygon(geom.coordinates)
  else if (geom.type === 'MultiPolygon') next.coordinates = geom.coordinates.map(projectPolygon)
  return { ...feature, geometry: next }
}

async function main() {
  const fc = await loadGeoJson()

  const projection = geoMercator().fitExtent(
    [
      [VIEWBOX_PAD, VIEWBOX_PAD],
      [VIEWBOX_WIDTH - VIEWBOX_PAD, VIEWBOX_HEIGHT - VIEWBOX_PAD],
    ],
    fc,
  )
  // Identity path generator — operates on already-projected coords. We project
  // manually first so we can run the simplifier in pixel space (tolerance is
  // in viewBox units).
  const path = geoPath()

  const regions = fc.features
    .map((feature) => {
      const meta = REGION_NAMES[feature.properties.NAME_1]
      if (!meta) {
        console.warn(`! Unknown NAME_1: ${feature.properties.NAME_1}`)
        return null
      }
      const projected = simplifyFeature(projectFeature(feature, projection), SIMPLIFY_TOLERANCE)
      const d = path(projected)
      if (!d) return null
      const projectedCentroid = path.centroid(projected)
      const geoCenter = geoCentroid(feature)
      return {
        id: meta.id,
        ru: meta.ru,
        kk: meta.kk,
        shortRu: meta.shortRu,
        shortKk: meta.shortKk,
        nameRaw: feature.properties.NAME_1,
        path: trimPath(d),
        labelX: round(projectedCentroid[0]),
        labelY: round(projectedCentroid[1]),
        geoLat: round(geoCenter[1], 4),
        geoLng: round(geoCenter[0], 4),
      }
    })
    .filter(Boolean)
    .sort((a, b) => a.ru.localeCompare(b.ru, 'ru'))

  const dealerCoords = DEALER_CITIES.map(({ id, lat, lng }) => {
    const [x, y] = projection([lng, lat]) ?? [0, 0]
    return { id, cx: round(x), cy: round(y) }
  })

  const banner = `// AUTO-GENERATED by scripts/build-kz-map.mjs — do not edit by hand.
// Source: GADM v4.1 admin-1 (Kazakhstan), Mercator-projected into the SVG
// viewBox below. Dealer pin coordinates are projected by the same script so
// they line up with the polygons. Re-run \`node scripts/build-kz-map.mjs\`
// after editing the source data.\n`

  const ts = [
    banner,
    `export const KZ_VIEWBOX = '0 0 ${VIEWBOX_WIDTH} ${VIEWBOX_HEIGHT}' as const\n`,
    `export interface KzRegion {`,
    `  /** Stable slug (latin, kebab-case). */`,
    `  id: string`,
    `  /** Russian display name (full, e.g. "Восточно-Казахстанская"). */`,
    `  ru: string`,
    `  /** Kazakh display name (full). */`,
    `  kk: string`,
    `  /** Russian short label for on-map rendering (e.g. "ВКО"). */`,
    `  shortRu: string`,
    `  /** Kazakh short label for on-map rendering. */`,
    `  shortKk: string`,
    `  /** SVG path d-attribute in viewBox coordinates. */`,
    `  path: string`,
    `  /** Suggested label anchor (visual centroid in viewBox coords). */`,
    `  labelX: number`,
    `  labelY: number`,
    `}\n`,
    `export const KZ_REGIONS: readonly KzRegion[] = [`,
    ...regions.map(
      (r) =>
        `  { id: ${JSON.stringify(r.id)}, ru: ${JSON.stringify(r.ru)}, kk: ${JSON.stringify(
          r.kk,
        )}, shortRu: ${JSON.stringify(r.shortRu)}, shortKk: ${JSON.stringify(
          r.shortKk,
        )}, path: ${JSON.stringify(r.path)}, labelX: ${r.labelX}, labelY: ${r.labelY} },`,
    ),
    `] as const\n`,
    `export interface KzDealerCoord {`,
    `  id: string`,
    `  cx: number`,
    `  cy: number`,
    `}\n`,
    `export const KZ_DEALER_COORDS: readonly KzDealerCoord[] = [`,
    ...dealerCoords.map(
      (c) => `  { id: ${JSON.stringify(c.id)}, cx: ${c.cx}, cy: ${c.cy} },`,
    ),
    `] as const\n`,
  ].join('\n')

  writeFileSync(OUT, ts, 'utf8')

  console.log(`Wrote ${OUT}`)
  console.log(`  regions: ${regions.length}`)
  console.log(`  dealers: ${dealerCoords.length}`)
  for (const c of dealerCoords) {
    console.log(`    ${c.id.padEnd(10)} cx=${c.cx} cy=${c.cy}`)
  }
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
